kind: pipeline
type: docker
name: default

steps:
  - name: test
    image: docker:25.0.4-cli
    volumes:
      - name: dockersock
        path: /var/run
    commands:
      - sleep 5
      - docker ps -a

  - name: build
    image: docker:25.0.4-cli
    volumes:
      - name: dockersock
        path: /var/run
    environment:
      DOCKER_USERNAME:
        from_secret: docker_username
      DOCKER_TOKEN:
        from_secret: docker_token
      PRIVATE_DOCKER_USERNAME:
        from_secret: private_docker_username
      PRIVATE_DOCKER_TOKEN:
        from_secret: private_docker_token
      PRIVATE_DOCKER_HUB:
        from_secret: private_docker_hub
    commands:
      - echo $DOCKER_TOKEN | docker login -u $DOCKER_USERNAME --password-stdin
      - docker build -t "eliyip/mdbook-katex:${DRONE_TAG##v}" .
      - docker tag "eliyip/mdbook-katex:${DRONE_TAG##v}" eliyip/mdbook-katex:latest
      - echo $PRIVATE_DOCKER_TOKEN | docker login $PRIVATE_DOCKER_HUB -u $PRIVATE_DOCKER_USERNAME --password-stdin
      - docker run -v /var/run/docker.sock:/var/run/docker.sock hub.momoai.me/slim:1.40.10 build --tag "eliyip/mdbook-katex:${DRONE_TAG##v}-slim" --target "eliyip/mdbook-katex:${DRONE_TAG##v}" --http-probe=false --include-shell --include-path "/app"
      - docker tag "eliyip/mdbook-katex:${DRONE_TAG##v}-slim" eliyip/mdbook-katex:latest-slim

  - name: publish
    image: docker:25.0.4-cli
    volumes:
      - name: dockersock
        path: /var/run
    environment:
      DOCKER_USERNAME:
        from_secret: docker_username
      DOCKER_TOKEN:
        from_secret: docker_token
    commands:
      - echo $DOCKER_TOKEN | docker login -u $DOCKER_USERNAME --password-stdin
      - |
        docker images eliyip/mdbook-katex --format "{{.Repository}}:{{.Tag}}" | while read image; do
          docker push "$image"
        done

services:
  - name: docker
    image: docker:25.0.4-dind
    privileged: true
    volumes:
      - name: dockersock
        path: /var/run

volumes:
  - name: dockersock
    temp: {}

trigger:
  event:
    - tag
